/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/loklok/Downloads/lok/loklok.glb -T -R 4096 -f avif -j -M -S --ratio 1.0 --output /Users/loklok/Downloads/lok/output-compressed/glb_2.jsx 
Files: /Users/loklok/Downloads/lok/loklok.glb [83.08KB] > /Users/loklok/Downloads/lok/output-compressed/loklok-transformed.glb [7.63KB] (91%)
*/
import { Center, MeshTransmissionMaterial, useGLTF } from '@react-three/drei'

export function LokLok(props) {
    const { nodes, materials } = useGLTF('/loklok-transformed.glb')
    return (
        <group>
            <Center>
                <group {...props} dispose={null}>
                    <mesh geometry={nodes.Text.geometry} position={[0.016, 0.337, 0]} rotation={[Math.PI / 2, 0, 0]} >
                        <MeshTransmissionMaterial thickness={2} reflectivity={0.25} metalness={0} color={'#f1d11b'} roughness={0} transmission={1}></MeshTransmissionMaterial>
                    </mesh>
                    <mesh geometry={nodes.Text001.geometry} scale={[1.5, 1.5, 1.5]} position={[-0.011, 1.575, 0]} rotation={[Math.PI / 2, 0, 0]} >
                        <MeshTransmissionMaterial thickness={2} reflectivity={0.25} metalness={0} color={'#f1d11b'} roughness={0} transmission={1}></MeshTransmissionMaterial>
                    </mesh>
                </group>
            </Center>
        </group>
    )
}

useGLTF.preload('/loklok-transformed.glb')
