/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/loklok/Downloads/lok/loklok.glb -T -R 4096 -f avif -j -M -S --ratio 1.0 --output /Users/loklok/Downloads/lok/output-compressed/glb_2.jsx 
Files: /Users/loklok/Downloads/lok/loklok.glb [83.08KB] > /Users/loklok/Downloads/lok/output-compressed/loklok-transformed.glb [7.63KB] (91%)
*/
import { Center, useGLTF } from '@react-three/drei'
import { DiamindComponent } from './DiamondTSL/DiamondComponent';
import { Suspense, useRef } from 'react';
import { useFrame } from '@react-three/fiber';

export function LokLok(props) {
    const { nodes, materials } = useGLTF('/loklok-transformed.glb')
    return (
        <group>
            <Center>
                <group {...props} dispose={null}>

                    <mesh geometry={nodes.Text.geometry} position={[0.016, 0.337, 0]} rotation={[Math.PI / 2, 0, 0]} >
                        <meshPhysicalNodeMaterial thickness={2} reflectivity={0.5} metalness={0} color={'#90daff'} roughness={0} transmission={1}></meshPhysicalNodeMaterial>
                    </mesh>

                    <group position={[0, 1, 0]}>
                        <Spinner>
                            <DiamindComponent />
                        </Spinner>
                    </group>

                    <mesh geometry={nodes.Text001.geometry} scale={[1.5, 1.5, 1.5]} position={[-0.011, 2.2, 0]} rotation={[Math.PI / 2, 0, 0]} >
                        <meshPhysicalNodeMaterial thickness={2} reflectivity={0.5} metalness={0} color={'#90daff'} roughness={0} transmission={1}></meshPhysicalNodeMaterial>
                    </mesh>
                </group>
            </Center>
        </group>
    )
}

function Spinner({ children }) {
    const ref = useRef(null);

    useFrame((_, dt) => {
        if (ref.current) {
            ref.current.rotation.y += dt * 0.125;
        }
    });

    return <group ref={ref}>{children}</group>;
}


useGLTF.preload('/loklok-transformed.glb')
