/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/loklok/Downloads/lok/loklok.glb -T -R 4096 -f avif -j -M -S --ratio 1.0 --output /Users/loklok/Downloads/lok/output-compressed/glb_2.jsx 
Files: /Users/loklok/Downloads/lok/loklok.glb [83.08KB] > /Users/loklok/Downloads/lok/output-compressed/loklok-transformed.glb [7.63KB] (91%)
*/

import { Center, useGLTF } from '@react-three/drei'

// import { DiamindComponent } from './DiamondTSL/DiamondComponent';
// import { Suspense, useRef } from 'react';
// import { useFrame } from '@react-three/fiber';

export function LokLok(props) {
    const { nodes, materials } = useGLTF('/loklok-transformed.glb')
    return (
        <group>
            <group {...props} dispose={null}>

                <mesh geometry={nodes.Text.geometry} position={[-1.5, -0.5, 0]} rotation={[Math.PI / 2 + 0.125 * -Math.PI, 0, 0]} >
                    <meshPhysicalNodeMaterial thickness={2} reflectivity={0.5} metalness={0} color={'#90daff'} roughness={0} transmission={1}></meshPhysicalNodeMaterial>
                </mesh>


                <mesh geometry={nodes.Text001.geometry} position={[1.5, -0.5, 0]} rotation={[Math.PI / 2 + 0.125 * -Math.PI, 0, 0]} >
                    <meshPhysicalNodeMaterial thickness={2} reflectivity={0.5} metalness={0} color={'#90daff'} roughness={0} transmission={1}></meshPhysicalNodeMaterial>
                </mesh>
            </group>
        </group>
    )
}

useGLTF.preload('/loklok-transformed.glb')
